### ISSUE TITLE
Timeseries data error

### ISSUE THREAD

**Issue by pooyadav** [me-box/app-twitter-sentiment#4]
waiting for DATABOX_STORE_BLOB_ENDPOINT https://app-twitter-sentiment-store-json:8080
Registering sentiment datasource
subscribing to datasources: https://driver-twitter-store-json:8080/twitterUserTimeLine 
TOSH [] https://driver-twitter-store-json:8080/twitterUserTimeLine
[Error getting timeseries.latest] TypeError: Cannot read property 'data' of undefined
    at databox.timeseries.latest.then (/src/main.js:101:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Toshbrown** [comment]
Works here with v0.0.2 see logs below - what are the steps to reproduce the error?

$docker service logs app-twitter-sentiment
app-twitter-sentiment.1.pquxa93n9104@moby    | npm info it worked if it ends with ok
app-twitter-sentiment.1.pquxa93n9104@moby    | npm info using npm@5.3.0
app-twitter-sentiment.1.pquxa93n9104@moby    | npm info using node@v8.2.0
app-twitter-sentiment.1.pquxa93n9104@moby    | npm info lifecycle app-twitter-sentiment@1.0.0~prestart: app-twitter-sentiment@1.0.0
app-twitter-sentiment.1.pquxa93n9104@moby    | npm info lifecycle app-twitter-sentiment@1.0.0~start: app-twitter-sentiment@1.0.0
app-twitter-sentiment.1.pquxa93n9104@moby    |
app-twitter-sentiment.1.pquxa93n9104@moby    | > app-twitter-sentiment@1.0.0 start /
app-twitter-sentiment.1.pquxa93n9104@moby    | > node ./src/main.js
app-twitter-sentiment.1.pquxa93n9104@moby    |
app-twitter-sentiment.1.pquxa93n9104@moby    | waiting for DATABOX_STORE_BLOB_ENDPOINT https://app-twitter-sentiment-store-json:8080
app-twitter-sentiment.1.pquxa93n9104@moby    | Registering sentiment datasource
app-twitter-sentiment.1.pquxa93n9104@moby    | subscribing to datasources: https://driver-twitter-store-json:8080/twitterUserTimeLine https://driver-twitter-store-json:8080/twitterHashTagStream
app-twitter-sentiment.1.pquxa93n9104@moby    | [subscribing] https://driver-twitter-store-json:8080/twitterHashTagStream
app-twitter-sentiment.1.pquxa93n9104@moby    | TOSH [ { _id: '5a0a0d2d5b55740032627058',
app-twitter-sentiment.1.pquxa93n9104@moby    |     datasource_id: 'twitterUserTimeLine',
app-twitter-sentiment.1.pquxa93n9104@moby    |     data:
app-twitter-sentiment.1.pquxa93n9104@moby    |      { created_at: 'Mon Nov 13 21:22:53 +0000 2017',
app-twitter-sentiment.1.pquxa93n9104@moby    |        id: 930184213676150800,
app-twitter-sentiment.1.pquxa93n9104@moby    |        id_str: '930184213676150784',
app-twitter-sentiment.1.pquxa93n9104@moby    |        text: 'The role drink played in the work of six talented American writers. From the archive https://t.co/283hiX7o7X',
app-twitter-sentiment.1.pquxa93n9104@moby    |        source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
app-twitter-sentiment.1.pquxa93n9104@moby    |        truncated: false,
app-twitter-sentiment.1.pquxa93n9104@moby    |        in_reply_to_status_id: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        in_reply_to_status_id_str: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        in_reply_to_user_id: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        in_reply_to_user_id_str: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        in_reply_to_screen_name: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        user: [Object],
app-twitter-sentiment.1.pquxa93n9104@moby    |        geo: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        coordinates: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        place: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        contributors: null,
app-twitter-sentiment.1.pquxa93n9104@moby    |        is_quote_status: false,
app-twitter-sentiment.1.pquxa93n9104@moby    |        quote_count: 0,
app-twitter-sentiment.1.pquxa93n9104@moby    |        reply_count: 0,
app-twitter-sentiment.1.pquxa93n9104@moby    |        retweet_count: 0,
app-twitter-sentiment.1.pquxa93n9104@moby    |        favorite_count: 0,
app-twitter-sentiment.1.pquxa93n9104@moby    |        entities: [Object],
app-twitter-sentiment.1.pquxa93n9104@moby    |        favorited: false,
app-twitter-sentiment.1.pquxa93n9104@moby    |        retweeted: false,
app-twitter-sentiment.1.pquxa93n9104@moby    |        possibly_sensitive: false,
app-twitter-sentiment.1.pquxa93n9104@moby    |        filter_level: 'low',
app-twitter-sentiment.1.pquxa93n9104@moby    |        lang: 'en',
app-twitter-sentiment.1.pquxa93n9104@moby    |        timestamp_ms: '1510608173184' },
app-twitter-sentiment.1.pquxa93n9104@moby    |     timestamp: 1510608173404 } ] https://driver-twitter-store-json:8080/twitterUserTimeLine
Toshs-MacBook-Pro:client tosh$
